#!/usr/bin/env python3
"""AUTO-IMPROVE — self-research loop for the key parser.

Mines NEW detection patterns from the open-source scanner ecosystem
(keyhunter/gitleaks/etc.), validates them, appends to patterns_extra.py,
and commits back to the repo so ALL nodes inherit improvements.

Runs before every hunt (workflow step) and can be run locally:
  python auto_improve.py [--no-push]
"""
import json
import os
import re
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

PROJ = Path(__file__).parent
EXTRA_FILE = PROJ / 'src' / 'patterns_extra.py'
META_FILE = PROJ / 'data' / 'auto_improve_meta.json'

# Research targets: (repo, ref, path, parser)
SOURCES = [
    ('fadidevv/keyhunter', 'HEAD', 'src/patterns.rs', 'rust'),
    ('gitleaks/gitleaks', 'HEAD', 'config/gitleaks.toml', 'toml'),
    ('mazen160/secrets-patterns-db', 'HEAD', 'rules-stable.yml', 'yaml-rules'),
]

# Placeholder/test strings — a good pattern must NOT match these
NEGATIVE_SAMPLES = [
    'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    'your_api_key_here', 'sk-test-123', 'AKIAIOSFODNN7EXAMPLE',
    'abcdefabcdefabcdefabcdefabcdefab',
    '00000000000000000000000000000000',
    'changeme', 'placeholder', 'example_key_1234567890',
]


def _token() -> str:
    tf = PROJ / 'gh_tokens.txt'
    try:
        for l in tf.read_text(encoding='utf-8').splitlines():
            l = l.strip()
            if l.startswith('ghp_'):
                return l
    except Exception:
        pass
    return os.environ.get('GITHUB_TOKEN', '') or os.environ.get('GH_TOKEN', '')


def fetch_raw(repo: str, ref: str, path: str) -> str:
    url = f'https://raw.githubusercontent.com/{repo}/{ref}/{path}'
    req = urllib.request.Request(url, headers={'User-Agent': 'auto-improve'})
    tok = _token()
    if tok:
        req.add_header('Authorization', f'token {tok}')
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.read().decode('utf-8', errors='ignore')
    except Exception as e:
        print(f'[improve] fetch fail {repo}/{path}: {e}')
        return ''


def parse_rust(text: str) -> dict:
    """keyhunter patterns.rs: m.insert("name", KeyPattern { ... regex: Regex::new(r"...")"""
    out = {}
    for m in re.finditer(r'm\.insert\(\s*"([\w-]+)".*?Regex::new\(\s*r"([^"]+)"', text, re.S):
        out['kh_' + m.group(1)] = m.group(2)
    return out


def parse_toml(text: str) -> dict:
    """gitleaks.toml: [[rules]] id = "..." regex = '''...'''"""
    out = {}
    for m in re.finditer(r'\[\[rules\]\]\s*id\s*=\s*"([^"]+)"(.*?)(?=\[\[rules\]\]|\Z)', text, re.S):
        rid, body = m.group(1), m.group(2)
        rm = re.search(r"regex\s*=\s*'''(.+?)'''|regex\s*=\s*\"(.+?)\"", body, re.S)
        if rm:
            out['gl_' + rid] = rm.group(1) or rm.group(2)
    return out


def parse_yaml_rules(text: str) -> dict:
    """secrets-patterns-db rules-stable.yml: - id/name + pattern"""
    out = {}
    for m in re.finditer(r'-\s+(?:id|name):\s*([\w.-]+)\s*\n(?:.*?\n)*?\s+pattern:\s*[\'"]?(.+?)[\'"]?\s*\n', text):
        out['sp_' + m.group(1)[:40]] = m.group(2)
    return out


PARSERS = {'rust': parse_rust, 'toml': parse_toml, 'yaml-rules': parse_yaml_rules}


def existing_patterns() -> set:
    have = set()
    kf = PROJ / 'src' / 'key_patterns.py'
    try:
        t = kf.read_text(encoding='utf-8', errors='ignore')
        for m in re.finditer(r're\.compile\(r?[\'"](.+?)[\'"]', t):
            have.add(m.group(1))
    except Exception:
        pass
    if EXTRA_FILE.exists():
        try:
            t = EXTRA_FILE.read_text(encoding='utf-8', errors='ignore')
            for m in re.finditer(r're\.compile\(r?[\'"](.+?)[\'"]', t):
                have.add(m.group(1))
        except Exception:
            pass
    return have


def validate(name: str, pattern: str) -> bool:
    try:
        rx = re.compile(pattern)
    except re.error:
        return False
    if len(pattern) < 8 or len(pattern) > 400:
        return False
    # must not match placeholders
    for s in NEGATIVE_SAMPLES:
        try:
            if rx.search(s):
                return False
        except Exception:
            return False
    # reject catastrophic backtracking risk: nested quantifiers
    if re.search(r'\(.+[+*]\)[+*]', pattern):
        return False
    # must contain at least one literal-ish char class or prefix
    if not re.search(r'[A-Za-z]{2}', pattern):
        return False
    return True


def load_meta() -> dict:
    try:
        return json.loads(META_FILE.read_text(encoding='utf-8'))
    except Exception:
        return {'runs': [], 'known': []}


def write_extra(patterns: dict):
    lines = ['"""AUTO-GENERATED by auto_improve.py — mined from the scanner ecosystem."""',
             'import re', '', 'EXTRA_PATTERNS = {']
    for name, pat in sorted(patterns.items()):
        safe = pat.replace("'", "\\'")
        lines.append(f"    {name!r}: re.compile(r'{safe}'),")
    lines.append('}')
    EXTRA_FILE.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def git_push(msg: str) -> bool:
    """Push mined patterns back via GitHub Contents API (works in Actions + locally)."""
    tok = _token() or os.environ.get('GITHUB_TOKEN')
    remote = os.environ.get('GITHUB_REPOSITORY', '')
    if not tok or not remote:
        print('[improve] no token/repo context — skip push (local mode)')
        return False
    import base64
    import urllib.error

    def api(path, method='GET', body=None):
        req = urllib.request.Request(f'https://api.github.com{path}', method=method)
        req.add_header('Authorization', f'token {tok}')
        req.add_header('Accept', 'application/vnd.github+json')
        if body is not None:
            req.data = json.dumps(body).encode()
            req.add_header('Content-Type', 'application/json')
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                b = r.read()
                return r.status, json.loads(b) if b else {}
        except urllib.error.HTTPError as e:
            try:
                return e.code, json.loads(e.read())
            except Exception:
                return e.code, {}

    ok = True
    for rel in ['src/patterns_extra.py', 'data/auto_improve_meta.json']:
        f = PROJ / rel
        if not f.exists():
            continue
        st, cur = api(f'/repos/{remote}/contents/{rel}')
        sha = cur.get('sha') if st == 200 else None
        body = {'message': msg, 'content': base64.b64encode(f.read_bytes()).decode()}
        if sha:
            body['sha'] = sha
        st2, _ = api(f'/repos/{remote}/contents/{rel}', method='PUT', body=body)
        if st2 not in (200, 201):
            print(f'[improve] push fail {rel}: {st2}')
            ok = False
    return ok


def main():
    no_push = '--no-push' in sys.argv
    meta = load_meta()
    known = set(meta.get('known', []))
    have = existing_patterns()
    added = {}

    for repo, ref, path, parser in SOURCES:
        text = fetch_raw(repo, ref, path)
        if not text:
            continue
        try:
            pats = PARSERS[parser](text)
        except Exception as e:
            print(f'[improve] parse fail {repo}: {e}')
            continue
        print(f'[improve] {repo}: {len(pats)} patterns found')
        for name, pat in pats.items():
            if name in known or pat in have:
                continue
            if len(added) >= 20:  # cap per run
                break
            if validate(name, pat):
                added[name] = pat

    # merge with existing extra patterns
    current = {}
    if EXTRA_FILE.exists():
        ns = {}
        try:
            exec(EXTRA_FILE.read_text(encoding='utf-8'), ns)
            current = {k: v.pattern for k, v in ns.get('EXTRA_PATTERNS', {}).items()}
        except Exception:
            pass
    merged = dict(current)
    merged.update(added)
    if merged:
        write_extra(merged)
    known.update(added.keys())
    meta['known'] = sorted(known)
    meta['runs'].append({'ts': int(time.time()), 'added': list(added.keys()),
                         'total': len(merged)})
    meta['runs'] = meta['runs'][-50:]
    META_FILE.parent.mkdir(parents=True, exist_ok=True)
    META_FILE.write_text(json.dumps(meta, indent=1), encoding='utf-8')

    print(f'[improve] added {len(added)} new patterns, total extra={len(merged)}')
    if added and not no_push:
        ok = git_push(f'auto-improve: +{len(added)} patterns')
        print('[improve] pushed' if ok else '[improve] push skipped/failed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
