"""Shared key patterns — generated from eternal_v10 PROVIDERS registry (34 providers)."""
import re

PATTERNS = [
    ('ZAI', re.compile(r'[a-f0-9]{32}\.[A-Za-z0-9]{10,30}')),
    ('KIMI', re.compile(r'sk-[A-Za-z0-9]{40,120}')),
    ('SAKANA', re.compile(r'fish_[a-f0-9]{64}')),
    ('OPENROUTER', re.compile(r'sk-or-v1-[0-9a-f]{48,70}')),
    ('DASHSCOPE', re.compile(r'sk-[a-f0-9]{32}')),
    ('MINIMAX', re.compile(r'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9\.[A-Za-z0-9_\-]{20,}\.[A-Za-z0-9_\-]{20,}')),
    ('DEEPSEEK', re.compile(r'sk-[a-f0-9]{32}')),
    ('TWOCAPTCHA', re.compile(r'(?:2captcha|rucaptcha|twocaptcha|two_captcha)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([a-zA-Z0-9]{32})', re.IGNORECASE)),
    ('CAPSOLVER', re.compile(r'(?:capsolver|cap_solver)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?(CAP-[A-Za-z0-9_-]{20,45})', re.IGNORECASE)),
    ('ANTICAPTCHA', re.compile(r'(?:anticaptcha|anti_captcha)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([a-f0-9]{32})', re.IGNORECASE)),
    ('WEBSHARE', re.compile(r'(?:webshare)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})', re.IGNORECASE)),
    ('IPROYAL', re.compile(r'(?:iproyal|ip_royal)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([a-zA-Z0-9_-]{20,50})', re.IGNORECASE)),
    ('BRIGHTDATA', re.compile(r'(?:brightdata|luminati|brd)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([a-f0-9]{32})', re.IGNORECASE)),
    ('TELEGRAM', re.compile(r'\b\d{8,10}:AA[A-Za-z0-9_\-]{33}\b')),
    ('DISCORD', re.compile(r'mfa\.[A-Za-z0-9_\-]{24,80}')),
    ('OPENAI', re.compile(r'sk-proj-[A-Za-z0-9_-]{60,200}'
                     r'|sk-svcacct-[A-Za-z0-9_-]{60,200}'
                     r'|sk-None-[A-Za-z0-9_-]{20,200}'
                     r'|"sk-[A-Za-z0-9]{20}iv|"sk-[A-Za-z0-9]{20}proj')),
    ('ANTHROPIC', re.compile(r'sk-ant-api03-[A-Za-z0-9_-]{20,120}')),
    ('ANTHROPIC_OAT', re.compile(r'sk-ant-oat01-(?=[A-Za-z0-9_-]{40,120}$)(?=[A-Za-z0-9_-]*\d)(?=[A-Za-z0-9_-]*[A-Z])[A-Za-z0-9_-]{40,120}')),
    ('GOOGLE', re.compile(r'AIza[A-Za-z0-9_-]{35}')),
    ('MISTRAL', re.compile(r'(?:mistral|MISTRAL)[_a-zA-Z]{0,15}["\']?\s*[=:]\s*["\']?([A-Za-z0-9]{32})(?![A-Za-z0-9])')),
    ('TOGETHER', re.compile(r'tgp_[A-Za-z0-9\-]{40,60}')),
    ('REPLICATE', re.compile(r'r8_[A-Za-z0-9]{37}')),
    ('SILICONFLOW', re.compile(r'sk-[a-zA-Z0-9]{48}')),
    ('FIREWORKS', re.compile(r'(?:fireworks|FIREWORKS)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([A-Za-z0-9]{48,52})', re.IGNORECASE)),
    ('FIREWORKS', re.compile(r'fw_[A-Za-z0-9]{40,60}')),
    ('GROQ', re.compile(r'gsk_[A-Za-z0-9]{40,60}')),
    ('COHERE', re.compile(r'(?:cohere|COHERE)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([A-Za-z0-9]{40})', re.IGNORECASE)),
    ('NOVITA', re.compile(r'(?:novita|NOVITA)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([A-Za-z0-9_-]{32,40})', re.IGNORECASE)),
    ('PERPLEXITY', re.compile(r'pplx-[a-z0-9]{56}')),
    ('ELEVENLABS', re.compile(r'(?:elevenlabs|ELEVENLABS|xi)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([a-f0-9]{32})', re.IGNORECASE)),
    ('STABILITY', re.compile(r'sk-[A-Za-z0-9]{99}')),
    ('ALIYUN', re.compile(r'LTAI[A-Za-z0-9]{12,20}')),
    ('NVIDIA', re.compile(r'nvapi-[A-Za-z0-9_-]{80,120}')),
    ('HUGGINGFACE', re.compile(r'hf_[A-Za-z0-9]{34}')),
    ('GROK', re.compile(r'xai-[A-Za-z0-9]{40,60}')),
    # v4 traffic & infra patterns
    ('AWS', re.compile(r'AKIA[A-Z0-9]{16}')),
    ('CLOUDFLARE', re.compile(r'(?:cf_|CF_)[A-Za-z0-9_-]{40,50}')),
    ('DISCORD', re.compile(r'[MN][A-Za-z\d]{23,}\.[\w-]{6}\.[\w-]{27,}')),
    ('STRIPE', re.compile(r'sk_live_[A-Za-z0-9]{24,}')),
    ('GITHUB_PAT', re.compile(r'ghp_[A-Za-z0-9]{36}')),
    ('GITHUB_OAUTH', re.compile(r'gho_[A-Za-z0-9]{36}')),
    # v5: fine-grained & SaaS prefixes (2026-09-28 wave)
    ('GITHUB_USER', re.compile(r'ghu_[A-Za-z0-9]{36,45}')),
    ('GITHUB_SERVER', re.compile(r'ghs_[A-Za-z0-9]{36,45}')),
    ('GITHUB_REFRESH', re.compile(r'ghr_[A-Za-z0-9]{76,90}')),
    ('GITHUB_FINE', re.compile(r'github_pat_[A-Za-z0-9_]{82}')),
    ('SLACK_BOT', re.compile(r'xoxb-[0-9]{8,12}-[0-9]{8,12}-[A-Za-z0-9]{20,24}')),
    ('SLACK_USER', re.compile(r'xoxp-[0-9]{8,12}-[0-9]{8,12}-[0-9]{8,12}-[A-Za-z0-9]{20,30}')),
    ('SLACK_APP', re.compile(r'xapp-[0-9]-[A-Za-z0-9-]{20,}')),
    ('LINEAR', re.compile(r'lin_api_[A-Za-z0-9]{40}')),
    ('CEREBRAS', re.compile(r'csk-[a-z0-9]{60}')),
    ('SENTRY', re.compile(r'sntrys_[A-Za-z0-9_\-]{60,}')),
    ('FIGMA', re.compile(r'figd_[A-Za-z0-9]{40}')),
    ('POSTMAN', re.compile(r'PMAK-[A-Za-z0-9]{24}-[A-Za-z0-9]{43}')),
    ('NOTION_BARE', re.compile(r'secret_[A-Za-z0-9]{43}')),
    ('UPSTASH', re.compile(r'upstash_[A-Za-z0-9]{30,40}')),
    ('NPM', re.compile(r'npm_[A-Za-z0-9]{36}')),
    ('PYPI', re.compile(r'pypi-[A-Za-z0-9_-]{50,}')),
    ('SENDGRID', re.compile(r'SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}')),
    ('TWILIO', re.compile(r'(?:twilio|TWILIO)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([a-f0-9]{32})', re.IGNORECASE)),
    ('NOTION', re.compile(r'(?:notion|NOTION)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?(secret_[A-Za-z0-9]{43})', re.IGNORECASE)),
    ('PINECONE', re.compile(r'(?:pinecone|PINECONE)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})', re.IGNORECASE)),
    ('WANDB', re.compile(r'(?:wandb|WANDB)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([a-f0-9]{40})', re.IGNORECASE)),
    ('RUNPOD', re.compile(r'(?:runpod|RUNPOD)[_a-z]{0,15}["\']?\s*[=:]\s*["\']?([A-Za-z0-9_-]{30,50})', re.IGNORECASE)),
    ('TWILIO_SK', re.compile('SK[0-9a-f]{32}')),
    ('GITLAB_PAT', re.compile('glpat-[0-9a-zA-Z_-]{20,}')),
    ('PG_URI', re.compile('postgres(?:ql)?://[^\\s\\"\'<>]{1,64}:[^\\s\\"\'@<>]{4,}@[^\\s\\"\'<>]+')),
    ('MYSQL_URI', re.compile('mysql://[^\\s\\"\'<>]{1,64}:[^\\s\\"\'@<>]{4,}@[^\\s\\"\'<>]+')),
    ('MONGO_URI', re.compile('mongodb(?:\\+srv)?://[^\\s\\"\'<>]{1,64}:[^\\s\\"\'@<>]{4,}@[^\\s\\"\'<>]+')),
    ('REDIS_URI', re.compile('rediss?://:[^\\s\\"\'@<>]{4,}@[^\\s\\"\'<>]+')),
    ('HTTPS_AUTH', re.compile('https://[^\\s\\"\'/:@<>]{1,64}:[^\\s\\"\'@/<>]{4,}@[^\\s\\"\'<>]+')),
    # v6: full-stack wave (2026-09-29): cloud/dev-tool/SaaS prefixes + PEM
    ('NEON', re.compile(r'napi_[A-Za-z0-9]{30,60}')),
    ('DROPBOX', re.compile(r'sl\.[A-Za-z0-9_-]{100,150}')),
    ('TWITTER', re.compile(r'AAAAAAAAA[A-Za-z0-9%]{50,90}')),
    ('BREVO', re.compile(r'xkeysib-[A-Za-z0-9]{16,64}-[A-Za-z0-9]{16,64}')),
    ('RESEND', re.compile(r're_[A-Za-z0-9]{28,50}')),
    ('MAILGUN', re.compile(r'\bkey-[a-f0-9]{32}\b')),
    ('SHOPIFY', re.compile(r'shp(?:at|ca|ss|pa|ua)_[a-fA-F0-9]{32}')),
    ('SQUARE', re.compile(r'sq0atp-[A-Za-z0-9_-]{22,60}')),
    ('SQUARE_SECRET', re.compile(r'sq0csp-[A-Za-z0-9_-]{40,60}')),
    ('STRIPE_WEBHOOK', re.compile(r'whsec_[A-Za-z0-9]{32,64}')),
    ('STRIPE_RESTRICTED', re.compile(r'rk_live_[A-Za-z0-9]{24,99}')),
    ('DIGITALOCEAN', re.compile(r'do[po]_v1_[a-f0-9]{64}')),
    ('DOCKER', re.compile(r'dckr_pat_[A-Za-z0-9_-]{30,}')),
    ('KAKAO', re.compile(r'KakaoAK [0-9a-f]{32}')),
    ('RUBYGEMS_PAT', re.compile(r'rubygems_[A-Za-z0-9]{30,}')),
    ('SONARQUBE', re.compile(r'squ_[A-Za-z0-9]{40,}')),
    ('GRAFANA', re.compile(r'glc_[A-Za-z0-9_-]{40,}')),
    ('LANGSMITH', re.compile(r'lsv2_(?:pt|sk)_[A-Za-z0-9]{40,}')),
    ('TAVILY', re.compile(r'tvly-[A-Za-z0-9]{26,48}')),
    ('FIRECRAWL', re.compile(r'fc-[a-f0-9]{32}')),
    ('NETLIFY', re.compile(r'nfp_[A-Za-z0-9]{40,46}')),
    ('RENDER', re.compile(r'rnd_[A-Za-z0-9]{32,}')),
    ('MAPBOX_SECRET', re.compile(r'sk\.eyJ[A-Za-z0-9_\-]{50,}')),
    ('HUBSPOT', re.compile(r'pat-(?:na|eu)\d-[A-Za-z0-9]{30,}')),
    ('AIRTABLE', re.compile(r'pat[A-Za-z0-9]{8,20}\.[A-Za-z0-9]{40,}')),
    ('SENTRY_DSN', re.compile(r'https://[a-f0-9]{32}@[a-z0-9.-]*sentry\.io/\d+')),
    ('PRIVATE_KEY', re.compile(r'-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]{0,6000}?-----END [A-Z ]*PRIVATE KEY-----')),
    ('MAILCHIMP', re.compile(r'\b[a-f0-9]{32}-us\d{1,2}\b')),
    ('ACCTOKEN', re.compile(r'access_token\$production\$[a-z0-9]{16}\$[a-f0-9]{32}')),
]

# ENV assignment patterns: VAR=value -> provider (from v10 registry vars)
_ENV_VARS = [
    ('DEEPSEEK_REASONER_API_KEY', 'DEEPSEEK'),
    ('ALIYUN_DASHSCOPE_API_KEY', 'DASHSCOPE'),
    ('CLAUDE_CODE_ACCESS_TOKEN', 'ANTHROPIC_OAT'),
    ('STABLE_DIFFUSION_API_KEY', 'STABILITY'),
    ('CLAUDE_CODE_OAUTH_TOKEN', 'ANTHROPIC_OAT'),
    ('QWEN_DASHSCOPE_API_KEY', 'DASHSCOPE'),
    ('TONGYI_QIANWEN_API_KEY', 'DASHSCOPE'),
    ('DEEPSEEK_CODER_API_KEY', 'DEEPSEEK'),
    ('ALIBABA_CLOUD_API_KEY', 'DASHSCOPE'),
    ('DASHSCOPE_LLM_API_KEY', 'DASHSCOPE'),
    ('DEEPSEEK_ACCESS_TOKEN', 'DEEPSEEK'),
    ('DEEPSEEK_CHAT_API_KEY', 'DEEPSEEK'),
    ('ANTHROPIC_OAUTH_TOKEN', 'ANTHROPIC_OAT'),
    ('HUGGINGFACE_API_TOKEN', 'HUGGINGFACE'),
    ('ALIBABACLOUD_API_KEY', 'DASHSCOPE'),
    ('ALIYUN_CLOUD_API_KEY', 'DASHSCOPE'),
    ('ALIBABA_QWEN_API_KEY', 'DASHSCOPE'),
    ('DEEPSEEK_PRO_API_KEY', 'DEEPSEEK'),
    ('NVIDIA_BUILD_API_KEY', 'NVIDIA'),
    ('OPEN_ROUTER_API_KEY', 'OPENROUTER'),
    ('ALIBABA_LLM_API_KEY', 'DASHSCOPE'),
    ('DASHSCOPE_API_TOKEN', 'DASHSCOPE'),
    ('ALIYUN_QWEN_API_KEY', 'DASHSCOPE'),
    ('DEEPSEEK_API_SECRET', 'DEEPSEEK'),
    ('DEEPSEEK_V3_API_KEY', 'DEEPSEEK'),
    ('DEEPSEEK_V4_API_KEY', 'DEEPSEEK'),
    ('DEEPSEEK_R1_API_KEY', 'DEEPSEEK'),
    ('TWO_CAPTCHA_API_KEY', 'TWOCAPTCHA'),
    ('TOGETHER_AI_API_KEY', 'TOGETHER'),
    ('REPLICATE_API_TOKEN', 'REPLICATE'),
    ('FIREWORKS_API_TOKEN', 'FIREWORKS'),
    ('OPENROUTER_API_KEY', 'OPENROUTER'),
    ('ALIYUN_LLM_API_KEY', 'DASHSCOPE'),
    ('MODELSCOPE_API_KEY', 'DASHSCOPE'),
    ('TWOCAPTCHA_API_KEY', 'TWOCAPTCHA'),
    ('OPENAI_PROJECT_KEY', 'OPENAI'),
    ('CLAUDE_OAUTH_TOKEN', 'ANTHROPIC_OAT'),
    ('MISTRAL_AI_API_KEY', 'MISTRAL'),
    ('PERPLEXITY_API_KEY', 'PERPLEXITY'),
    ('SAKANA_AI_API_KEY', 'SAKANA'),
    ('DASHSCOPE_API_KEY', 'DASHSCOPE'),
    ('BAILIAN_API_TOKEN', 'DASHSCOPE'),
    ('RUCAPTCHA_API_KEY', 'TWOCAPTCHA'),
    ('OPENAI_SECRET_KEY', 'OPENAI'),
    ('ANTHROPIC_API_KEY', 'ANTHROPIC'),
    ('GOOGLE_AI_API_KEY', 'GOOGLE'),
    ('MISTRALAI_API_KEY', 'MISTRAL'),
    ('REPLICATE_API_KEY', 'REPLICATE'),
    ('FIREWORKS_API_KEY', 'FIREWORKS'),
    ('STABILITY_API_KEY', 'STABILITY'),
    ('HUGGINGFACE_TOKEN', 'HUGGINGFACE'),
    ('BIGMODEL_API_KEY', 'ZAI'),
    ('MOONSHOT_API_KEY', 'KIMI'),
    ('OPENROUTER_TOKEN', 'OPENROUTER'),
    ('ALICLOUD_API_KEY', 'DASHSCOPE'),
    ('MODELSCOPE_TOKEN', 'DASHSCOPE'),
    ('DEEPSEEK_API_KEY', 'DEEPSEEK'),
    ('2CAPTCHA_API_KEY', 'TWOCAPTCHA'),
    ('ANTHROPIC_APIKEY', 'ANTHROPIC'),
    ('GOOGLE_API_TOKEN', 'GOOGLE'),
    ('TOGETHER_API_KEY', 'TOGETHER'),
    ('PERPLEXITY_TOKEN', 'PERPLEXITY'),
    ('ZHIPUAI_API_KEY', 'ZAI'),
    ('CHATGLM_API_KEY', 'ZAI'),
    ('OPEN_ROUTER_KEY', 'OPENROUTER'),
    ('ALIBABA_API_KEY', 'DASHSCOPE'),
    ('DASHSCOPE_TOKEN', 'DASHSCOPE'),
    ('BAILIAN_API_KEY', 'DASHSCOPE'),
    ('QIANWEN_API_KEY', 'DASHSCOPE'),
    ('QWEN2_5_API_KEY', 'DASHSCOPE'),
    ('DEEPSEEK_SECRET', 'DEEPSEEK'),
    ('CAPTCHA_API_KEY', 'TWOCAPTCHA'),
    ('TWO_CAPTCHA_KEY', 'TWOCAPTCHA'),
    ('ANTHROPIC_TOKEN', 'ANTHROPIC'),
    ('MISTRAL_API_KEY', 'MISTRAL'),
    ('TOGETHER_AI_KEY', 'TOGETHER'),
    ('REPLICATE_TOKEN', 'REPLICATE'),
    ('FIREWORKS_TOKEN', 'FIREWORKS'),
    ('STABILITY_TOKEN', 'STABILITY'),
    ('BIGMODEL_TOKEN', 'ZAI'),
    ('SAKANA_API_KEY', 'SAKANA'),
    ('OPENROUTER_KEY', 'OPENROUTER'),
    ('ALIYUN_API_KEY', 'DASHSCOPE'),
    ('TONGYI_API_KEY', 'DASHSCOPE'),
    ('DEEPSEEK_TOKEN', 'DEEPSEEK'),
    ('2CAPTCHA_TOKEN', 'TWOCAPTCHA'),
    ('OPENAI_API_KEY', 'OPENAI'),
    ('CLAUDE_API_KEY', 'ANTHROPIC'),
    ('GOOGLE_API_KEY', 'GOOGLE'),
    ('GEMINI_API_KEY', 'GOOGLE'),
    ('PERPLEXITY_KEY', 'PERPLEXITY'),
    ('NVIDIA_API_KEY', 'NVIDIA'),
    ('ZHIPU_API_KEY', 'ZAI'),
    ('DASHSCOPE_KEY', 'DASHSCOPE'),
    ('QWEN2_API_KEY', 'DASHSCOPE'),
    ('RUCAPTCHA_KEY', 'TWOCAPTCHA'),
    ('CAPTCHA_TOKEN', 'TWOCAPTCHA'),
    ('ANTHROPIC_KEY', 'ANTHROPIC'),
    ('MISTRAL_TOKEN', 'MISTRAL'),
    ('REPLICATE_KEY', 'REPLICATE'),
    ('FIREWORKS_KEY', 'FIREWORKS'),
    ('STABILITY_KEY', 'STABILITY'),
    ('Z_AI_API_KEY', 'ZAI'),
    ('GLM4_API_KEY', 'ZAI'),
    ('GLM5_API_KEY', 'ZAI'),
    ('BIGMODEL_KEY', 'ZAI'),
    ('KIMI_API_KEY', 'KIMI'),
    ('FUGU_API_KEY', 'SAKANA'),
    ('FISH_API_KEY', 'SAKANA'),
    ('QWEN_API_KEY', 'DASHSCOPE'),
    ('DEEPSEEK_KEY', 'DEEPSEEK'),
    ('2CAPTCHA_KEY', 'TWOCAPTCHA'),
    ('OPENAI_TOKEN', 'OPENAI'),
    ('TOGETHER_KEY', 'TOGETHER'),
    ('PPLX_API_KEY', 'PERPLEXITY'),
    ('HF_API_TOKEN', 'HUGGINGFACE'),
    ('ZAI_API_KEY', 'ZAI'),
    ('GLM_API_KEY', 'ZAI'),
    ('ZHIPUAI_KEY', 'ZAI'),
    ('CHATGLM_KEY', 'ZAI'),
    ('ALI_API_KEY', 'DASHSCOPE'),
    ('CAPTCHA_KEY', 'TWOCAPTCHA'),
    ('GCP_API_KEY', 'GOOGLE'),
    ('MISTRAL_KEY', 'MISTRAL'),
    ('NIM_API_KEY', 'NVIDIA'),
    ('SAKANA_KEY', 'SAKANA'),
    ('OR_API_KEY', 'OPENROUTER'),
    ('OPENROUTER', 'OPENROUTER'),
    ('QWEN_TOKEN', 'DASHSCOPE'),
    ('DS_API_KEY', 'DEEPSEEK'),
    ('OPENAI_KEY', 'OPENAI'),
    ('CLAUDE_KEY', 'ANTHROPIC'),
    ('NVIDIA_KEY', 'NVIDIA'),
    ('ZHIPU_KEY', 'ZAI'),
    ('Z_AI_KEY', 'ZAI'),
    ('OR_TOKEN', 'OPENROUTER'),
    ('QWEN_KEY', 'DASHSCOPE'),
    ('PPLX_KEY', 'PERPLEXITY'),
    ('HF_TOKEN', 'HUGGINGFACE'),
    ('ZAI_KEY', 'ZAI'),
    ('HUGGINGFACEHUB_API_TOKEN', 'HUGGINGFACE'),
    ('FIREWORKS_AI_API_KEY', 'FIREWORKS'),
    ('NVIDIA_NIM_API_KEY', 'NVIDIA'),
    ('MINIMAX_API_KEY', 'MINIMAX'),
    ('GROQ_LLM_API_KEY', 'GROQ'),
    ('NOVITA_API_KEY', 'NOVITA'),
    ('COHERE_API_KEY', 'COHERE'),
    ('ELEVENLABS_API_KEY', 'ELEVENLABS'),
    ('GROQ_API_KEY', 'GROQ'),
    ('XI_API_KEY', 'ELEVENLABS'),
    ('XAI_API_KEY', 'GROK'),
    ('GROQ_TOKEN', 'GROQ'),
    ('NVIDIA_NIM', 'NVIDIA'),
    # v4 traffic & infra ENV vars
    ('AWS_ACCESS_KEY_ID', 'AWS'),
    ('AWS_SECRET_ACCESS_KEY', 'AWS'),
    ('AZURE_CLIENT_SECRET', 'AZURE'),
    ('CLOUDFLARE_API_TOKEN', 'CLOUDFLARE'),
    ('CF_API_TOKEN', 'CLOUDFLARE'),
    ('DIGITALOCEAN_TOKEN', 'DIGITALOCEAN'),
    ('DO_TOKEN', 'DIGITALOCEAN'),
    ('VULTR_API_KEY', 'VULTR'),
    ('LINODE_TOKEN', 'LINODE'),
    ('HEROKU_API_KEY', 'HEROKU'),
    ('VERCEL_TOKEN', 'VERCEL'),
    ('NETLIFY_AUTH_TOKEN', 'NETLIFY'),
    ('RUNPOD_API_KEY', 'RUNPOD'),
    ('MODAL_TOKEN', 'MODAL'),
    ('LAMBDA_API_KEY', 'LAMBDA'),
    ('PINECONE_API_KEY', 'PINECONE'),
    ('WEAVIATE_API_KEY', 'WEAVIATE'),
    ('QDRANT_API_KEY', 'QDRANT'),
    ('WANDB_API_KEY', 'WANDB'),
    ('LANGCHAIN_API_KEY', 'LANGCHAIN'),
    ('LANGSMITH_API_KEY', 'LANGCHAIN'),
    ('DISCORD_BOT_TOKEN', 'DISCORD'),
    ('DISCORD_TOKEN', 'DISCORD'),
    ('SLACK_BOT_TOKEN', 'SLACK'),
    ('NOTION_API_KEY', 'NOTION'),
    ('NOTION_TOKEN', 'NOTION'),
    ('SENDGRID_API_KEY', 'SENDGRID'),
    ('MAILGUN_API_KEY', 'MAILGUN'),
    ('TWILIO_AUTH_TOKEN', 'TWILIO'),
    ('STRIPE_SECRET_KEY', 'STRIPE'),
    ('NPM_TOKEN', 'NPM'),
    ('PYPI_TOKEN', 'PYPI'),
    ('GITHUB_TOKEN', 'GITHUB'),
    ('JWT_SECRET', 'GENERIC_SECRET'),
    ('SESSION_SECRET', 'GENERIC_SECRET'),
    # v6 env vars: new SaaS/dev-tool providers
    ('TAVILY_API_KEY', 'TAVILY'),
    ('FIRECRAWL_API_KEY', 'FIRECRAWL'),
    ('RESEND_API_KEY', 'RESEND'),
    ('BREVO_API_KEY', 'BREVO'),
    ('SENDINBLUE_API_KEY', 'BREVO'),
    ('SHOPIFY_ACCESS_TOKEN', 'SHOPIFY'),
    ('SHOPIFY_ADMIN_ACCESS_TOKEN', 'SHOPIFY'),
    ('SONAR_TOKEN', 'SONARQUBE'),
    ('SONARQUBE_TOKEN', 'SONARQUBE'),
    ('GRAFANA_TOKEN', 'GRAFANA'),
    ('GRAFANA_API_TOKEN', 'GRAFANA'),
    ('RUBYGEMS_AUTH_TOKEN', 'RUBYGEMS_PAT'),
    ('NEON_API_KEY', 'NEON'),
    ('TWITTER_BEARER_TOKEN', 'TWITTER'),
    ('MAPBOX_ACCESS_TOKEN', 'MAPBOX_SECRET'),
    ('MAPBOX_TOKEN', 'MAPBOX_SECRET'),
    ('DOCKER_HUB_TOKEN', 'DOCKER'),
    ('MAILCHIMP_API_KEY', 'MAILCHIMP'),
    ('MAILCHIMP_KEY', 'MAILCHIMP'),
    ('NETLIFY_TOKEN', 'NETLIFY'),
]

_VAR2PROV = dict(_ENV_VARS)
_ALT = '|'.join(dict(_ENV_VARS))
ENV_RE = re.compile(
    '\\b(' + _ALT + ')\\b\\s*[=:]\\s*[\'"]?([A-Za-z0-9_\\-.]{20,200})'
)


def scan_text(text):
    """Yield (prov, key) from text via PATTERNS + ENV assignments."""
    out = []
    for prov, rx in PATTERNS:
        for m in rx.findall(text or ""):
            out.append((prov, m))
    for m in ENV_RE.finditer(text or ""):
        out.append((_VAR2PROV.get(m.group(1), "ENV"), m.group(2)))
    return out
