"""
KeyHunter Shared Key Patterns — single source of truth.

All scanners import from here to ensure consistent, precise key detection.
Patterns are derived from REAL working keys in the DB (verified formats).

IMPORTANT: These patterns are PREFIX-based only (no generic patterns like
[a-f0-9]{64} which catch SHA-256 hashes).
"""
import re

# === VERIFIED KEY PATTERNS (from real WORKING keys) ===
# Each pattern matches ONLY the real format, nothing generic.
KEY_PATTERNS = {
    # ZAI/ZhipuAI: 32 hex . 10-30 alnum (e.g. 26cd829b...SAFM)
    "ZAI": re.compile(r'[a-f0-9]{32}\.[A-Za-z0-9]{10,30}'),

    # DASHSCOPE (Qwen): sk- + exactly 32 hex (total 35 chars)
    "DASHSCOPE": re.compile(r'sk-[a-f0-9]{32}'),

    # OPENROUTER: sk-or-v1- + 64 hex (total 73 chars, verified)
    "OPENROUTER": re.compile(r'sk-or-v1-[a-f0-9]{64}'),

    # GROQ: disabled (free tier only, no value)

    # REPLICATE: r8_ + 37 alnum (total 40 chars, verified)
    "REPLICATE": re.compile(r'r8_[A-Za-z0-9]{37}'),

    # NVIDIA NIM: nvapi- + 30-100 chars
    "NVIDIA": re.compile(r'nvapi-[A-Za-z0-9_-]{30,100}'),

    # SAKANA: fish_ + 64 hex
    "SAKANA": re.compile(r'fish_[a-f0-9]{64}'),

    # PERPLEXITY: pplx- + 56 alnum
    "PERPLEXITY": re.compile(r'pplx-[a-z0-9]{56}'),

    # CAPSOLVER: CAP- + 32 hex uppercase
    "CAPSOLVER": re.compile(r'CAP-[A-Z0-9]{32}'),

    # DEEPSEEK: sk- + 32 hex (SAME format as DASHSCOPE — cross-check in validator)
    # NOT included here to avoid double-matching. Validator handles it.
    # Validator tests each DASHSCOPE-format key against BOTH APIs.

    # DEEPSEEK-specific env var detection (caught by ENV_RE context)
    # When DEEPSEEK_API_KEY=sk-xxxx appears, validator tries DeepSeek first.
}

# KIMI pattern — NARROW: sk- + exactly 48 alnum (total 51, verified)
# Old pattern was sk-[A-Za-z0-9]{40,120} → 96% false positive rate.
# Real KIMI keys are 51 chars: sk- + 48 mixed case alnum.
KIMI_PATTERN = re.compile(r'sk-[A-Za-z0-9]{48}')

# Env var names that indicate a key follows (context-aware extraction)
ENV_RE = re.compile(
    r'(?:DASHSCOPE_API_KEY|ZHIPU_API_KEY|Z_AI_API_KEY|BIGMODEL_API_KEY|'
    r'ZAI_API_KEY|GLM_API_KEY|CHATGLM_API_KEY|ZHIPUAI_API_KEY|'
    r'OPENROUTER_API_KEY|MOONSHOT_API_KEY|'
    r'KIMI_API_KEY|DEEPSEEK_API_KEY|DEEPSEEK_KEY|DS_API_KEY|'
    r'REPLICATE_API_TOKEN|'
    r'TOGETHER_API_KEY|FIREWORKS_API_KEY|NVIDIA_API_KEY|NIM_API_KEY|'
    r'SILICONFLOW_API_KEY|'
    r'PERPLEXITY_API_KEY|PPLX_API_KEY|'
    r'SAKANA_API_KEY|FUGU_API_KEY|FISH_API_KEY|'
    # Alibaba Cloud / Aliyun / Bailian / ModelScope
    r'ALIBABACLOUD_API_KEY|ALIYUN_CLOUD_API_KEY|ALICLOUD_API_KEY|'
    r'ALIYUN_LLM_API_KEY|ALIBABA_LLM_API_KEY|ALIBABA_CLOUD_API_KEY|'
    r'BAILIAN_API_KEY|BAILIAN_API_TOKEN|'
    r'QWEN_DASHSCOPE_API_KEY|TONGYI_QIANWEN_API_KEY|QIANWEN_API_KEY|'
    r'ALIYUN_QWEN_API_KEY|ALIBABA_QWEN_API_KEY|'
    r'MODELSCOPE_API_KEY|MODELSCOPE_TOKEN|DASHSCOPE_LLM_API_KEY)'
    r'\s*[=:]\s*["\']?([A-Za-z0-9_\-\.]{20,120})["\']?', re.IGNORECASE)




# AUTO-IMPROVE: optional mined patterns (patterns_extra.py generated by auto_improve.py)
EXTRA_PATTERNS = {}
try:
    from patterns_extra import EXTRA_PATTERNS as _EP
    EXTRA_PATTERNS = dict(_EP)
except Exception:
    pass

def extract_all_keys(text: str) -> list:
    """Extract all keys from text. Returns [(provider, key)].

    Uses BOTH prefix patterns AND env-var context.
    Env-var context catches keys without known prefixes (TOGETHER, COHERE).
    Filters out placeholders, examples, and template values.
    """
    keys = []

    # Placeholder patterns to reject (case-insensitive)
    PLACEHOLDER_WORDS = (
        'your_', 'your-', 'xxxxx', 'placeholder', 'example', 'dummy',
        'fake_', 'fake-', 'test_key', 'testkey', 'sample', 'demo_',
        'replace', 'insert', 'paste', 'todo', 'changeme', 'change_me',
        'put_here', 'add_here', 'fill_', 'enter_', 'set_', 'get_',
        'api_key_here', '_here', 'key_here', 'token_here',
        'none', 'null', 'undefined', 'secret_key', 'my_api_key',
        'actualkey', 'apikey', 'sk-xxx', 'sk-your', 'xxxxxxxx',
    )

    def is_placeholder(val: str) -> bool:
        low = val.lower()
        # Reject obvious placeholders
        if any(w in low for w in PLACEHOLDER_WORDS):
            return True
        # Reject if mostly x's (template)
        x_count = low.count('x')
        if x_count > len(val) * 0.4:
            return True
        # Reject if all same char
        if len(set(low)) <= 2:
            return True
        # Reject "YOUR_XXX" style (all caps with underscores, < 30 chars)
        if val.isupper() and '_' in val and len(val) < 40:
            return True
        return False

    # 1. Env-var context extraction (catches TOGETHER, COHERE, etc)
    for m in ENV_RE.finditer(text):
        val = m.group(1).strip().strip('"\'')
        if len(val) >= 20 and not is_placeholder(val):
            if val not in [k for _, k in keys]:
                keys.append(("ENV", val))

    # 2. Prefix-pattern extraction (ZAI, DASHSCOPE, OPENROUTER, etc)
    for prov, pattern in KEY_PATTERNS.items():
        for m in pattern.finditer(text):
            keys.append((prov, m.group(0)))

    # 3. KIMI — narrow pattern (only exact 51-char length)
    for m in KIMI_PATTERN.finditer(text):
        keys.append(("KIMI", m.group(0)))

    # 4. AUTO-IMPROVE mined patterns (dedup against already-found keys)
    _seen_vals = {k for _, k in keys}
    for name, pattern in EXTRA_PATTERNS.items():
        try:
            for m in pattern.finditer(text):
                val = m.group(0)
                if val in _seen_vals or is_placeholder(val):
                    continue
                keys.append((name.upper()[:32], val))
                _seen_vals.add(val)
        except Exception:
            continue

    return keys
