"""AUTO-GENERATED by auto_improve.py — mined from the scanner ecosystem."""
import re

EXTRA_PATTERNS = {
    'kh_anthropic': re.compile(r'sk-ant-api03-[A-Za-z0-9_-]{93}'),
    'kh_aws_secret': re.compile(r'[A-Za-z0-9/+=]{40}'),
    'kh_azure': re.compile(r'[a-zA-Z0-9+/]{86}=='),
    'kh_cohere': re.compile(r'[a-zA-Z0-9]{40}'),
    'kh_fireworks': re.compile(r'fw_[A-Za-z0-9]{32,}'),
    'kh_google': re.compile(r'AIza[0-9A-Za-z_-]{35}'),
    'kh_grok': re.compile(r'xai-[A-Za-z0-9]{48,}'),
    'kh_groq': re.compile(r'gsk_[A-Za-z0-9]{52,}'),
    'kh_huggingface': re.compile(r'hf_[A-Za-z0-9]{34,}'),
    'kh_mailchimp': re.compile(r'[a-f0-9]{32}-us[0-9]{1,2}'),
    'kh_mailgun': re.compile(r'key-[a-f0-9]{32}'),
    'kh_openai': re.compile(r'sk-[A-Za-z0-9]{20}T3BlbkFJ[A-Za-z0-9]{20}|sk-proj-[A-Za-z0-9_-]{48,180}|sk-[a-zA-Z0-9]{48}'),
    'kh_paypal': re.compile(r'access_token\$production\$[a-z0-9]{16}\$[a-f0-9]{32}'),
    'kh_perplexity': re.compile(r'pplx-[A-Za-z0-9]{48,}'),
    'kh_replicate': re.compile(r'r8_[A-Za-z0-9]{38,}'),
    'kh_sendgrid': re.compile(r'SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}'),
    'kh_square': re.compile(r'sq0[a-z]{3}-[0-9A-Za-z_-]{22,50}'),
    'kh_stripe_live': re.compile(r'sk_live_[0-9a-zA-Z]{24,99}'),
    'kh_stripe_restricted': re.compile(r'rk_live_[0-9a-zA-Z]{24,99}'),
    'kh_twilio': re.compile(r'SK[a-f0-9]{32}'),
}
